# Generated by Django 5.1.4 on 2025-01-13 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_services', '0002_maildomain_mailbox'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailbox',
            options={'ordering': ('local_part', 'mail_domain')},
        ),
        migrations.RenameField(
            model_name='mailbox',
            old_name='address',
            new_name='local_part',
        ),
        migrations.AlterUniqueTogether(
            name='mailbox',
            unique_together={('local_part', 'mail_domain')},
        ),
    ]
